spring:
  redis :
    uri : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    port: xxxxxxxxxxxx
    password : xxxxxxxxxxxxxxxxx
  data:
    mongodb:
      uri:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      database: xxxxxxxxxxx
      auto-index-creation: true
  main:
    allow-circular-references: true
  mail :
    host : xxxxxxxxxx
    port : xxxxxx
    username : xxxxxxxxxxxxxxxxx
    password : xxxx xxxx xxxx xxxx
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true

server:
  port: 8080

logging:
  level:
    com:
      example:
        journalApp: DEBUG

weather:
  api:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
